# Generated by Django 4.1.7 on 2023-04-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='category',
            field=models.CharField(choices=[('analyste_vente', 'analyste_vente'), ('Responsable_vente_et_achat', 'Responsable_vente_et_achat'), ('analyste_achat', 'analyste_achat')], max_length=190, null=True),
        ),
    ]
