# Generated by Django 4.1.7 on 2023-04-09 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_gère_alter_utilisateur_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='gère',
            name='administrateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.administrateur'),
        ),
        migrations.AddField(
            model_name='gère',
            name='utilisateur',
            field=models.ManyToManyField(to='config.utilisateur'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='category',
            field=models.CharField(choices=[('Responsable_vente_et_achat', 'Responsable_vente_et_achat'), ('analyste_vente', 'analyste_vente'), ('analyste_achat', 'analyste_achat')], max_length=190, null=True),
        ),
    ]
