# Generated by Django 4.1.7 on 2023-04-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_gère_administrateur_gère_utilisateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gère',
            name='status',
            field=models.CharField(choices=[('desactivated', 'desactivated'), ('created', 'created'), ('updated', 'updated')], max_length=190, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='category',
            field=models.CharField(choices=[('analyste_achat', 'analyste_achat'), ('analyste_vente', 'analyste_vente'), ('Responsable_vente_et_achat', 'Responsable_vente_et_achat')], max_length=190, null=True),
        ),
    ]
