# Generated by Django 4.1.7 on 2023-04-20 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_gère_status_alter_utilisateur_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gère',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('updated', 'updated'), ('desactivated', 'desactivated')], max_length=190, null=True),
        ),
        migrations.RemoveField(
            model_name='gère',
            name='utilisateur',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='category',
            field=models.CharField(choices=[('Responsable_vente_et_achat', 'Responsable_vente_et_achat'), ('analyste_achat', 'analyste_achat'), ('analyste_vente', 'analyste_vente')], max_length=190, null=True),
        ),
        migrations.AddField(
            model_name='gère',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.utilisateur'),
        ),
    ]
