# Generated by Django 4.1.7 on 2023-05-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_alter_gère_status_remove_gère_utilisateur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='kes',
            fields=[
                ('nkes', models.AutoField(primary_key=True, serialize=False)),
                ('nomkes', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='category',
            field=models.CharField(choices=[('analyste_vente', 'analyste_vente'), ('Responsable_vente_et_achat', 'Responsable_vente_et_achat'), ('analyste_achat', 'analyste_achat')], max_length=190, null=True),
        ),
    ]
