# Generated by Django 4.1.7 on 2023-05-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_kes_alter_utilisateur_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Congechauffeur',
            fields=[
                ('Numero_Conge', models.AutoField(primary_key=True, serialize=False)),
                ('nbr_jours', models.IntegerField(null=True)),
                ('date_debut', models.DateField(null=True)),
                ('date_fin', models.DateField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='category',
            field=models.CharField(choices=[('analyste_achat', 'analyste_achat'), ('analyste_vente', 'analyste_vente'), ('Responsable_vente_et_achat', 'Responsable_vente_et_achat')], max_length=190, null=True),
        ),
    ]
