# Generated by Django 4.1.7 on 2023-05-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_congechauffeur_alter_utilisateur_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='kes',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='category',
            field=models.CharField(choices=[('analyste_vente', 'analyste_vente'), ('analyste_achat', 'analyste_achat'), ('Responsable_vente_et_achat', 'Responsable_vente_et_achat')], max_length=190, null=True),
        ),
    ]
