# Generated by Django 4.1.7 on 2023-05-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_kes_date_created_alter_utilisateur_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gère',
            name='status',
            field=models.CharField(choices=[('updated', 'updated'), ('delete', 'delete'), ('created', 'created')], max_length=190, null=True),
        ),
    ]
