# Generated by Django 4.1.7 on 2023-05-16 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=190, null=True)),
                ('prix_article', models.PositiveIntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bon_de_commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=190, null=True)),
                ('date', models.CharField(max_length=190, null=True)),
                ('prix', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bon_de_commande_achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_achat', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bon_de_commande_vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_de_vente', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=190, null=True)),
                ('prénom', models.CharField(max_length=190, null=True)),
                ('cin', models.CharField(max_length=190, null=True)),
                ('num_tel', models.CharField(max_length=190, null=True)),
                ('adresse', models.CharField(max_length=190, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=190, null=True)),
                ('prénom', models.CharField(max_length=190, null=True)),
                ('cin', models.CharField(max_length=190, null=True)),
                ('num_tel', models.CharField(max_length=190, null=True)),
                ('adresse', models.CharField(max_length=190, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable_vente_et_achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=190, null=True)),
                ('prénom', models.CharField(max_length=190, null=True)),
                ('email', models.CharField(max_length=190, null=True)),
                ('mot_de_passe', models.CharField(max_length=190, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gère',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('updated', 'updated'), ('delete', 'delete'), ('created', 'created')], max_length=190, null=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venteachat.article')),
                ('bon_de_commande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venteachat.bon_de_commande')),
                ('bon_de_commande_achat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venteachat.bon_de_commande_achat')),
                ('bon_de_commande_vente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venteachat.bon_de_commande_vente')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venteachat.client')),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venteachat.fournisseur')),
                ('responsable_vente_et_achat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venteachat.responsable_vente_et_achat')),
            ],
        ),
    ]
