# Generated by Django 4.1.7 on 2023-05-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venteachat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('vendu', 'vendu'), ('acheté', 'acheté')], max_length=190, null=True),
        ),
        migrations.AlterField(
            model_name='gère',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('delete', 'delete'), ('updated', 'updated')], max_length=190, null=True),
        ),
    ]
