# Generated by Django 4.1.7 on 2023-05-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venteachat', '0002_article_status_alter_gère_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bon_de_commande',
            name='quantité',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
