# Generated by Django 5.0.7 on 2024-08-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venteachat', '0003_bon_de_commande_quantité'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='status',
        ),
        migrations.AlterField(
            model_name='gère',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('updated', 'updated'), ('delete', 'delete')], max_length=190, null=True),
        ),
    ]
